services:

  mysql:
    image: mysql:8.0
    container_name: product-api-mysql
    environment:
      MYSQL_DATABASE: productdb
      MYSQL_ROOT_PASSWORD: Pass@123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
